version: '3'

services:
  db:
    image: mysql:5.7 #mariadb
    restart: always
    ports:
      - 127.0.0.1:33061:3306
    networks:
      - wpsite
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
  wp:
    build:
      context: ./docker
      dockerfile: Dockerfile-wp.docker
    ports:
      - 8000:80
    volumes:
      - ./docker/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./app:/var/www/html
      # - ./app/wp-content:/var/www/html/wp-content
    depends_on:
      - db
    networks:
      - wpsite
    environment:
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_HOST: db
      WP_DEBUG: 1
  # nginx:
  #   volumes:
  #     - ./docker/nginx:/etc/nginx/conf.d
  #     - ./app:/var/www/html
  #   ports:
  #     - 8000:80 #8080
  #   networks:
  #     - wpsite
  #   #links:
  #   #  - wp
networks:
  wpsite:
volumes:
  db_data:
